blank_issues_enabled: false
contact_links:
  - name: Errors upon installation
    url: https://github.com/discordjs/opus/issues?q=is%3Aissue+error+install
    about: Most, if not all installation issues, are due to lacking build dependencies. Please check other related issues before opening another.
